create table if not exists public.household_snapshots (
  household_id text primary key,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.price_history (
  id bigint generated by default as identity primary key,
  household_id text not null,
  product_id text not null,
  product_name text not null default '',
  store_id text not null,
  store_name text not null default '',
  price numeric not null check (price > 0),
  promotion text not null default 'none',
  matched_name text not null default '',
  source_url text not null default '',
  actor text not null default '',
  checked_at timestamptz not null default now()
);

create index if not exists price_history_lookup_idx
  on public.price_history (household_id, product_id, store_id, checked_at desc);

-- Legacy table kept for migration compatibility with v2 clients.
create table if not exists public.user_snapshots (
  user_id text primary key,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.household_snapshots enable row level security;
alter table public.price_history enable row level security;
alter table public.user_snapshots enable row level security;

-- The serverless/local Node backend uses SUPABASE_SERVICE_ROLE_KEY.
-- Never expose the service-role key in config.js or browser code.
