create table if not exists public.household_snapshots (
  household_id text primary key,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.price_history (
  id bigint generated by default as identity primary key,
  household_id text not null,
  product_id text not null,
  product_name text not null default '',
  store_id text not null,
  store_name text not null default '',
  price numeric not null check (price > 0),
  promotion text not null default 'none',
  matched_name text not null default '',
  source_url text not null default '',
  actor text not null default '',
  checked_at timestamptz not null default now()
);

create index if not exists price_history_lookup_idx
  on public.price_history (household_id, product_id, store_id, checked_at desc);

-- Legacy table kept for migration compatibility with v2 clients.
create table if not exists public.user_snapshots (
  user_id text primary key,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.household_snapshots enable row level security;
alter table public.price_history enable row level security;
alter table public.user_snapshots enable row level security;

grant select, insert, update on public.household_snapshots to anon;
grant select, insert on public.price_history to anon;
grant usage, select on all sequences in schema public to anon;

drop policy if exists household_snapshots_select_by_household on public.household_snapshots;
create policy household_snapshots_select_by_household
on public.household_snapshots for select to anon
using (household_id = coalesce((current_setting('request.headers', true)::jsonb ->> 'x-household-id'), ''));

drop policy if exists household_snapshots_insert_by_household on public.household_snapshots;
create policy household_snapshots_insert_by_household
on public.household_snapshots for insert to anon
with check (household_id = coalesce((current_setting('request.headers', true)::jsonb ->> 'x-household-id'), ''));

drop policy if exists household_snapshots_update_by_household on public.household_snapshots;
create policy household_snapshots_update_by_household
on public.household_snapshots for update to anon
using (household_id = coalesce((current_setting('request.headers', true)::jsonb ->> 'x-household-id'), ''))
with check (household_id = coalesce((current_setting('request.headers', true)::jsonb ->> 'x-household-id'), ''));

drop policy if exists price_history_select_by_household on public.price_history;
create policy price_history_select_by_household
on public.price_history for select to anon
using (household_id = coalesce((current_setting('request.headers', true)::jsonb ->> 'x-household-id'), ''));

drop policy if exists price_history_insert_by_household on public.price_history;
create policy price_history_insert_by_household
on public.price_history for insert to anon
with check (household_id = coalesce((current_setting('request.headers', true)::jsonb ->> 'x-household-id'), ''));

-- The browser never receives a service-role key. Vercel can use the public
-- SUPABASE_PUBLISHABLE_KEY together with the household-scoped RLS policies above.
